# DIRM SPECIFIC

# NEEDED FOR MOUSE JIGGLER
DEFERRED_EXEC_ENABLE = yes
# CAPS WORD
CAPS_WORD_ENABLE = yes
TAP_DANCE_ENABLE = yes
# COMBOS
COMBO_ENABLE = yes
# DYNAMIC MACROS
DYNAMIC_MACRO_ENABLE = yes
